name: proschool
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  alarmplayer: ^1.1.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_html: null
  flutter_windowmanager: ^0.2.0
  freezed_annotation: ^2.4.1
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  kiosk_mode: ^0.5.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
